spring.datasource.username = postgres
spring.datasource.password = Okechukwu0
spring.datasource.url = jdbc:postgresql://database-2.cwcvuvtesdyi.us-east-1.rds.amazonaws.com:5432/groupchatdb?user=postgres&amp;password=Okechukwu0


